[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#000000"
blue = "#7aa6da"
cyan = "#70c0ba"
green = "#b9ca4a"
magenta = "#c397d8"
red = "#d54e53"
white = "#eaeaea"
yellow = "#e6c547"

[colors.primary]
background = "#111111"
bright_foreground = "#ffffff"
dim_foreground = "#9a9a9a"
foreground = "#eaeaea"

[colors.selection]
background = "#404040"
text = "#eaeaea"

[cursor]
style = "Beam"

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
style = "Bold"
family = "BitstromWera Nerd Font Mono"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
style = "Oblique"
family = "BitstromWera Nerd Font Mono"

[font.normal]
family = "BitstromWera Nerd Font Mono"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

# [mouse.double_click]
# threshold = 300
#
# [mouse.triple_click]
# threshold = 300

# [schemes.hybrid.bright]
# black = "#484c52"
# blue = "#96b1c9"
# cyan = "#9fc9c3"
# green = "#dffebe"
# magenta = "#bfa5c7"
# red = "#d27c7b"
# white = "#fcf7e2"
# yellow = "#f0d189"
#
# [schemes.hybrid.normal]
# black = "#35383b"
# blue = "#7693ac"
# cyan = "#749e99"
# green = "#769972"
# magenta = "#977ba0"
# red = "#b05655"
# white = "#848b92"
# yellow = "#e1a574"
#
# [schemes.hybrid.primary]
# background = "#27292c"
# foreground = "#d0d2d1"
#
# [schemes.onedark.bright]
# black = "0x3e4452"
# blue = "0x61afef"
# cyan = "0x56b6c2"
# green = "0x98c379"
# magenta = "0xc678dd"
# red = "0xe06c75"
# white = "0xabb2bf"
# yellow = "0xe5c07b"
#
# [schemes.onedark.cursor]
# cursor = "0x5c6370"
# text = "0x2c323c"
#
# [schemes.onedark.normal]
# black = "0x2c323c"
# blue = "0x61afef"
# cyan = "0x56b6c2"
# green = "0x98c379"
# magenta = "0xc678dd"
# red = "0xe06c75"
# white = "0x5c6370"
# yellow = "0xe5c07b"
#
# [schemes.onedark.primary]
# background = "0x282c34"
# foreground = "0xabb2bf"
#
# [schemes.onedark.selection]
# background = "0x3e4452"
# text = "CellForeground"
#
# [schemes.tomorrow.cursor]
# cursor = "#ffffff"
# text = "#000000"
#
# [schemes.tomorrow.normal]
# black = "#000000"
# blue = "#7aa6da"
# cyan = "#70c0ba"
# green = "#b9ca4a"
# magenta = "#c397d8"
# red = "#d54e53"
# white = "#eaeaea"
# yellow = "#e6c547"
#
# [schemes.tomorrow.primary]
# background = "#111111"
# bright_foreground = "#ffffff"
# dim_foreground = "#9a9a9a"
# foreground = "#eaeaea"
#
# [schemes.tomorrow.selection]
# background = "#404040"
# text = "#eaeaea"
#
[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
opacity = 1.0
dynamic_padding = false

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 2
y = 2

[general]
live_config_reload = true
